soc: qcom: build cpu_ops driver only on ARM64
The cpu_ops driver was created for ARM64 build only.  Let's use a
Kconfig option to enforce it, so that we can remove the compile issue
see on ARM below.

drivers/soc/qcom/cpu_ops.c:31:10: fatal error: asm/cpu_ops.h: No such file or directory
 #include <asm/cpu_ops.h>
          ^~~~~~~~~~~~~~~

Signed-off-by: Shawn Guo <shawn.guo@linaro.org>
Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>